const employees = [
  {
    id: 1,
    name: "John Doe",
    position: "Software Engineer",
    department: "IT",
    avatar: "https://img.daisyui.com/images/profile/demo/2@94.webp",
    country: "United States",
    email: "john.doe@example.com",
    address: "123 Elm Street, Springfield, IL",
    mobile: "+1 555-123-4567",
    dateOfJoining: "2020-01-15",
    salary: "$80,000",
    equipmentsIssued: [
      { type: "Laptop", dateOfIssue: "2022-03-01" },
      { type: "Desktop", dateOfIssue: "2023-06-15" },
    ],
    linkedin: "https://www.linkedin.com/in/johndoe",
    performanceMetrics: "Exceeds expectations in project delivery.",
    projects: ["Project A", "Project B"],
    certifications: ["Certified JavaScript Developer"],
    education: "B.Sc. in Computer Science",
    skills: ["JavaScript", "React", "Node.js"],
    languages: ["English", "Spanish"],
    emergencyContact: "Jane Doe - +1 555-987-6543",
    workHistory: "Previous roles include Junior Developer at XYZ Inc.",
    hobbies: ["Photography", "Cycling"],
    departmentHead: "Michael Scott",
    teamMembers: ["Pam Beesly", "Jim Halpert"],
    training: ["Advanced React Workshop"],
    workSchedule: "Mon-Fri, 9 AM - 5 PM",
    companyContributions: ["Led the initiative for remote work tools"],
    monthlyLeaves: 2,
    allowances: {
      HRA: "$1,200",
      TA: "$800",
      PF: "$400",
    },
  },
  {
    id: 2,
    name: "Alice Smith",
    position: "Project Manager",
    department: "Marketing",
    avatar: "https://img.daisyui.com/images/profile/demo/3@94.webp",
    country: "Canada",
    email: "alice.smith@example.com",
    address: "456 Maple Avenue, Toronto, ON",
    mobile: "+1 416-555-9876",
    dateOfJoining: "2019-11-01",
    salary: "$95,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2022-07-10" }],
    linkedin: "https://www.linkedin.com/in/alicesmith",
    performanceMetrics: "Outstanding in project execution.",
    projects: ["Campaign X", "Strategy Y"],
    certifications: ["Certified Scrum Master"],
    education: "MBA in Marketing",
    skills: ["Project Management", "Marketing Strategy"],
    languages: ["English", "French"],
    emergencyContact: "Bob Smith - +1 416-555-1234",
    workHistory: "Previous roles include Marketing Specialist at ABC Corp.",
    hobbies: ["Reading", "Traveling"],
    departmentHead: "Sarah Johnson",
    teamMembers: ["Tom Clark", "Nancy Davis"],
    training: ["Leadership Skills Workshop"],
    workSchedule: "Mon-Fri, 8 AM - 4 PM",
    companyContributions: ["Implemented new marketing strategies"],
    monthlyLeaves: 3,
    allowances: {
      HRA: "$1,500",
      TA: "$900",
      PF: "$500",
    },
  },
  {
    id: 3,
    name: "Michael Brown",
    position: "UX Designer",
    department: "Design",
    avatar: "https://img.daisyui.com/images/profile/demo/4@94.webp",
    country: "United Kingdom",
    email: "michael.brown@example.com",
    address: "789 High Street, London",
    mobile: "+44 20 7946 0958",
    dateOfJoining: "2021-06-12",
    salary: "$70,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2021-07-01" }],
    linkedin: "https://www.linkedin.com/in/michaelbrown",
    performanceMetrics: "Excellent in user interface design.",
    projects: ["Website Redesign", "Mobile App UX"],
    certifications: ["Certified UX Designer"],
    education: "M.A. in User Experience Design",
    skills: ["UX Design", "Wireframing", "Prototyping"],
    languages: ["English"],
    emergencyContact: "Sarah Brown - +44 20 7946 0959",
    workHistory: "Previous roles include Junior Designer at Design Studio.",
    hobbies: ["Sketching", "Gaming"],
    departmentHead: "Emma Wilson",
    teamMembers: ["Olivia Taylor", "Liam Johnson"],
    training: ["Advanced UX Techniques"],
    workSchedule: "Mon-Fri, 10 AM - 6 PM",
    companyContributions: ["Redesigned the company website"],
    monthlyLeaves: 1,
    allowances: {
      HRA: "$1,000",
      TA: "$700",
      PF: "$350",
    },
  },
  {
    id: 4,
    name: "Sophia Johnson",
    position: "Data Analyst",
    department: "Analytics",
    avatar: "https://img.daisyui.com/images/profile/demo/5@94.webp",
    country: "Australia",
    email: "sophia.johnson@example.com",
    address: "321 Oak Road, Sydney",
    mobile: "+61 2 9876 5432",
    dateOfJoining: "2022-02-20",
    salary: "$85,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2022-03-01" }],
    linkedin: "https://www.linkedin.com/in/sophiajohnson",
    performanceMetrics: "Excellent in data analysis and reporting.",
    projects: ["Sales Data Analysis", "Customer Insights"],
    certifications: ["Certified Data Analyst"],
    education: "B.Sc. in Statistics",
    skills: ["Data Analysis", "SQL", "Excel"],
    languages: ["English"],
    emergencyContact: "David Johnson - +61 2 9876 5433",
    workHistory: "Previous roles include Data Intern at Data Solutions.",
    hobbies: ["Hiking", "Cooking"],
    departmentHead: "Natalie Harris",
    teamMembers: ["James Brown", "Emily White"],
    training: ["Advanced Data Analytics"],
    workSchedule: "Mon-Fri, 9 AM - 5 PM",
    companyContributions: ["Improved data reporting processes"],
    monthlyLeaves: 2,
    allowances: {
      HRA: "$1,100",
      TA: "$750",
      PF: "$400",
    },
  },
  {
    id: 5,
    name: "Ethan Williams",
    position: "Marketing Specialist",
    department: "Marketing",
    avatar: "https://img.daisyui.com/images/profile/demo/6@94.webp",
    country: "Germany",
    email: "ethan.williams@example.com",
    address: "654 Birch Lane, Berlin",
    mobile: "+49 30 12345678",
    dateOfJoining: "2018-08-23",
    salary: "$75,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2018-09-01" }],
    linkedin: "https://www.linkedin.com/in/ethanwilliams",
    performanceMetrics: "Great in digital marketing campaigns.",
    projects: ["SEO Optimization", "Social Media Campaign"],
    certifications: ["Certified Digital Marketer"],
    education: "B.A. in Marketing",
    skills: ["SEO", "Social Media Marketing"],
    languages: ["English", "German"],
    emergencyContact: "Lena Williams - +49 30 12345679",
    workHistory: "Previous roles include Marketing Coordinator at XYZ Ltd.",
    hobbies: ["Traveling", "Cooking"],
    departmentHead: "Laura Green",
    teamMembers: ["Lucas Schmidt", "Isabella Müller"],
    training: ["Digital Marketing Strategies"],
    workSchedule: "Mon-Fri, 10 AM - 6 PM",
    companyContributions: ["Led successful marketing campaigns"],
    monthlyLeaves: 3,
    allowances: {
      HRA: "$1,300",
      TA: "$850",
      PF: "$450",
    },
  },
  {
    id: 6,
    name: "Olivia Taylor",
    position: "Content Writer",
    department: "Content",
    avatar: "https://img.daisyui.com/images/profile/demo/7@94.webp",
    country: "New Zealand",
    email: "olivia.taylor@example.com",
    address: "789 Cedar Street, Wellington",
    mobile: "+64 4 123 4567",
    dateOfJoining: "2021-04-10",
    salary: "$65,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2021-05-01" }],
    linkedin: "https://www.linkedin.com/in/oliviataylor",
    performanceMetrics: "Excellent in content creation and editing.",
    projects: ["Website Content", "Blog Posts"],
    certifications: ["Certified Content Writer"],
    education: "B.A. in English Literature",
    skills: ["Content Writing", "Editing"],
    languages: ["English"],
    emergencyContact: "Mia Taylor - +64 4 123 4568",
    workHistory: "Previous roles include Freelance Writer at WriteRight.",
    hobbies: ["Reading", "Yoga"],
    departmentHead: "Emily Scott",
    teamMembers: ["James Wilson", "Charlotte Harris"],
    training: ["Advanced Writing Skills"],
    workSchedule: "Mon-Fri, 9 AM - 5 PM",
    companyContributions: ["Enhanced website content quality"],
    monthlyLeaves: 1,
    allowances: {
      HRA: "$900",
      TA: "$600",
      PF: "$300",
    },
  },
  {
    id: 7,
    name: "Liam Johnson",
    position: "Software Tester",
    department: "QA",
    avatar: "https://img.daisyui.com/images/profile/demo/8@94.webp",
    country: "India",
    email: "liam.johnson@example.com",
    address: "123 Main Road, Bangalore",
    mobile: "+91 80 12345678",
    dateOfJoining: "2019-12-01",
    salary: "$72,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2020-01-01" }],
    linkedin: "https://www.linkedin.com/in/liamjohnson",
    performanceMetrics: "Great in identifying and reporting bugs.",
    projects: ["QA Testing", "Bug Reports"],
    certifications: ["Certified Software Tester"],
    education: "B.Tech in Computer Science",
    skills: ["Software Testing", "Automation Testing"],
    languages: ["English", "Hindi"],
    emergencyContact: "Sophie Johnson - +91 80 12345679",
    workHistory: "Previous roles include QA Intern at TestLab.",
    hobbies: ["Cricket", "Reading"],
    departmentHead: "Rajesh Patel",
    teamMembers: ["Amit Sharma", "Priya Singh"],
    training: ["Software Testing Tools"],
    workSchedule: "Mon-Fri, 10 AM - 6 PM",
    companyContributions: ["Improved bug tracking process"],
    monthlyLeaves: 2,
    allowances: {
      HRA: "$1,000",
      TA: "$700",
      PF: "$350",
    },
  },
  {
    id: 8,
    name: "Emma Wilson",
    position: "HR Manager",
    department: "HR",
    avatar: "https://img.daisyui.com/images/profile/demo/9@94.webp",
    country: "South Africa",
    email: "emma.wilson@example.com",
    address: "456 Sunset Blvd, Cape Town",
    mobile: "+27 21 123 4567",
    dateOfJoining: "2017-09-15",
    salary: "$85,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2017-10-01" }],
    linkedin: "https://www.linkedin.com/in/emmawilson",
    performanceMetrics: "Excellent in employee relations.",
    projects: ["Recruitment Drive", "Employee Engagement"],
    certifications: ["Certified HR Manager"],
    education: "M.A. in Human Resources",
    skills: ["Human Resources", "Employee Relations"],
    languages: ["English"],
    emergencyContact: "John Wilson - +27 21 123 4568",
    workHistory: "Previous roles include HR Coordinator at PeopleFirst.",
    hobbies: ["Gardening", "Cooking"],
    departmentHead: "Linda Davis",
    teamMembers: ["Sara Johnson", "Michael Lee"],
    training: ["Leadership Development"],
    workSchedule: "Mon-Fri, 8 AM - 4 PM",
    companyContributions: ["Revamped employee benefits program"],
    monthlyLeaves: 3,
    allowances: {
      HRA: "$1,200",
      TA: "$800",
      PF: "$400",
    },
  },
  {
    id: 9,
    name: "Noah Martinez",
    position: "Systems Analyst",
    department: "IT",
    avatar: "https://img.daisyui.com/images/profile/demo/10@94.webp",
    country: "Brazil",
    email: "noah.martinez@example.com",
    address: "789 Pine Street, São Paulo",
    mobile: "+55 11 1234-5678",
    dateOfJoining: "2020-05-05",
    salary: "$78,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2020-06-01" }],
    linkedin: "https://www.linkedin.com/in/noahmartinez",
    performanceMetrics: "Strong in system analysis and documentation.",
    projects: ["System Upgrade", "Process Optimization"],
    certifications: ["Certified Systems Analyst"],
    education: "B.Sc. in Information Technology",
    skills: ["Systems Analysis", "Database Management"],
    languages: ["Portuguese", "English"],
    emergencyContact: "Laura Martinez - +55 11 1234-5679",
    workHistory:
      "Previous roles include IT Support Specialist at TechSolutions.",
    hobbies: ["Swimming", "Traveling"],
    departmentHead: "Carlos Silva",
    teamMembers: ["Fernanda Oliveira", "João Pereira"],
    training: ["Advanced Systems Analysis"],
    workSchedule: "Mon-Fri, 9 AM - 5 PM",
    companyContributions: ["Optimized internal processes"],
    monthlyLeaves: 2,
    allowances: {
      HRA: "$1,100",
      TA: "$750",
      PF: "$400",
    },
  },
  {
    id: 10,
    name: "Isabella Miller",
    position: "Business Analyst",
    department: "Business",
    avatar: "https://img.daisyui.com/images/profile/demo/11@94.webp",
    country: "Italy",
    email: "isabella.miller@example.com",
    address: "321 Willow Street, Milan",
    mobile: "+39 02 12345678",
    dateOfJoining: "2018-07-01",
    salary: "$82,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2018-08-01" }],
    linkedin: "https://www.linkedin.com/in/isabellamiller",
    performanceMetrics: "Excellent in business requirements analysis.",
    projects: ["Market Research", "Business Strategy"],
    certifications: ["Certified Business Analyst"],
    education: "B.A. in Business Administration",
    skills: ["Business Analysis", "Market Research"],
    languages: ["Italian", "English"],
    emergencyContact: "Marco Miller - +39 02 12345679",
    workHistory: "Previous roles include Business Intern at BizCorp.",
    hobbies: ["Skiing", "Photography"],
    departmentHead: "Giovanni Rossi",
    teamMembers: ["Chiara Bianchi", "Luca Ferrari"],
    training: ["Advanced Business Analysis"],
    workSchedule: "Mon-Fri, 9 AM - 5 PM",
    companyContributions: ["Improved market analysis processes"],
    monthlyLeaves: 2,
    allowances: {
      HRA: "$1,100",
      TA: "$700",
      PF: "$350",
    },
  },
  {
    id: 11,
    name: "James Wilson",
    position: "Web Developer",
    department: "Development",
    avatar: "https://img.daisyui.com/images/profile/demo/12@94.webp",
    country: "Japan",
    email: "james.wilson@example.com",
    address: "654 Cherry Avenue, Tokyo",
    mobile: "+81 3-1234-5678",
    dateOfJoining: "2019-10-05",
    salary: "$77,000",
    equipmentsIssued: [{ type: "Laptop", dateOfIssue: "2019-11-01" }],
    linkedin: "https://www.linkedin.com/in/jameswilson",
    performanceMetrics: "Strong in web development and frontend technologies.",
    projects: ["E-commerce Platform", "Corporate Website"],
    certifications: ["Certified Frontend Developer"],
    education: "B.Sc. in Web Development",
    skills: ["HTML", "CSS", "JavaScript"],
    languages: ["Japanese", "English"],
    emergencyContact: "Yuki Wilson - +81 3-1234-5679",
    workHistory: "Previous roles include Junior Developer at WebWorks.",
    hobbies: ["Gaming", "Traveling"],
    departmentHead: "Hiroshi Tanaka",
    teamMembers: ["Miyu Nakamura", "Kenta Suzuki"],
    training: ["Advanced Web Development"],
    workSchedule: "Mon-Fri, 10 AM - 6 PM",
    companyContributions: ["Developed key web applications"],
    monthlyLeaves: 2,
    allowances: {
      HRA: "$1,000",
      TA: "$700",
      PF: "$350",
    },
  },
];

export default employees;
